import { Link } from 'react-router-dom'
import { Shield } from 'lucide-react'

export default function Privacy() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 h-[400px] w-[400px] rounded-full bg-primary/5 blur-[100px]" />
      </div>

      <header className="relative border-b border-border/50 py-4 px-6">
        <Link to="/" className="flex items-center gap-2 w-fit">
          <div className="h-7 w-7 rounded-lg bg-primary flex items-center justify-center glow-primary-sm">
            <Shield className="h-4 w-4 text-primary-foreground" />
          </div>
          <span className="font-space text-[15px] font-semibold tracking-tight">EDON</span>
        </Link>
      </header>

      <main className="relative flex-1 px-4 py-16">
        <div className="max-w-2xl mx-auto">
          <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">Legal</p>
          <h1 className="font-space text-3xl font-bold tracking-tight mb-2">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-10">Last updated: April 2026</p>

          <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
            <Section title="1. Information we collect">
              We collect information you provide directly when creating an account, submitting a contact form, or communicating with us. This includes your name, work email, company name, and usage data generated by your connected agents.
            </Section>
            <Section title="2. How we use your information">
              We use the information we collect to provide, maintain, and improve our services; send transactional and operational emails; respond to your requests and inquiries; and comply with legal obligations.
            </Section>
            <Section title="3. Data retention">
              Audit log retention depends on your plan (7 days on Hobby up to 365 days on Business). Enterprise customers may configure custom retention up to 7 years. You may request deletion of your data at any time.
            </Section>
            <Section title="4. Data sharing">
              We do not sell your data. We share data only with sub-processors required to operate our service (cloud infrastructure, email delivery) and only to the extent necessary. A full sub-processor list is available on request.
            </Section>
            <Section title="5. Security">
              EDON applies encryption in transit (TLS 1.2+) and at rest. Audit records are cryptographically hashed to ensure tamper-evidence. We conduct regular security reviews and penetration tests.
            </Section>
            <Section title="6. Your rights">
              Depending on your jurisdiction you may have the right to access, correct, or delete your personal data. To exercise these rights contact us at{' '}
              <a href="mailto:privacy@edoncore.com" className="text-primary hover:underline">privacy@edoncore.com</a>.
            </Section>
            <Section title="7. Contact">
              Questions about this policy? Email{' '}
              <a href="mailto:privacy@edoncore.com" className="text-primary hover:underline">privacy@edoncore.com</a>.
            </Section>
          </div>
        </div>
      </main>

      <footer className="relative border-t border-border/50 py-6 px-6">
        <div className="max-w-2xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <span className="text-xs text-muted-foreground/50">© {new Date().getFullYear()} EDON. All rights reserved.</span>
          <div className="flex items-center gap-4 text-xs text-muted-foreground/60">
            <Link to="/terms" className="hover:text-foreground transition-colors">Terms</Link>
            <Link to="/contact" className="hover:text-foreground transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="font-space text-base font-semibold text-foreground mb-2">{title}</h2>
      <p>{children}</p>
    </div>
  )
}
