"""EDON Hardening Agents — HTTP API routes.

POST /v1/hardening/run          — trigger a full coverage → policy → regression cycle
GET  /v1/hardening/status       — last run summary + agent enable flags
GET  /v1/hardening/rule-ready   — rules generated by policy agent, pending deployment
POST /v1/hardening/rule-ready/{proposal_id}/deploy — mark a rule_ready rule as applied
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Optional

from fastapi import APIRouter, Query, Request

from ..tenancy import get_request_tenant_id
from ..logging_config import get_logger

logger = get_logger(__name__)
router = APIRouter(prefix="/v1/hardening", tags=["hardening"])

# In-memory cache of last run result per tenant — lightweight, no DB needed
_last_results: dict[str, dict] = {}


def get_last_hardening_result(tenant_id: str | None) -> dict:
    """Public accessor for the last hardening result. Use this instead of
    importing _last_results directly from other modules."""
    return _last_results.get(tenant_id or "__global__", {})


@router.post("/run")
async def run_hardening(
    request: Request,
    force: bool = Query(False, description="Skip interval gate and run immediately"),
    max_coverage_states: int = Query(10, le=50),
    max_policy_proposals: int = Query(20, le=100),
    regression_trace_limit: int = Query(40, le=200),
):
    """Trigger a full hardening cycle: coverage → policy → regression.

    Coverage agent probes unscenarioed Impact failure states with synthetic
    shadow traces, generating new fix proposals.

    Policy agent converts approved fix proposals into deployable rule deltas
    (status: rule_ready). These are NOT applied — they require human confirm.

    Regression agent validates every rule_ready rule against recent trace
    history and reports which rules are safe to apply vs which cause regressions.

    All three agents are fail-open. Errors in one agent don't stop the others.
    """
    from ..agents.hardening.runner import run
    from ..impact.store import get_impact_store
    from ..shadow.trace_capture import get_trace_store

    governor = getattr(request.app.state, "governor", None)
    tenant_id = get_request_tenant_id(request)

    result = await run(
        governor=governor,
        impact_store=get_impact_store(),
        shadow_store=get_trace_store(),
        tenant_id=tenant_id,
        force=force,
        max_coverage_states=max_coverage_states,
        max_policy_proposals=max_policy_proposals,
        regression_trace_limit=regression_trace_limit,
    )

    _last_results[tenant_id or "__global__"] = result
    try:
        from ..persistence import get_db
        get_db().save_hardening_result(tenant_id or "__global__", result)
    except Exception as _persist_err:
        logger.warning("[hardening] DB persist failed (in-memory only): %s", _persist_err)
    return result


@router.get("/status")
async def get_hardening_status(request: Request):
    """Return last hardening run summary and agent enable flags."""
    import os
    tenant_id = get_request_tenant_id(request)
    last = _last_results.get(tenant_id or "__global__")

    return {
        "last_run": last,
        "agents": {
            "coverage":   os.getenv("EDON_HARDENING_COVERAGE_ENABLED",   "true") == "true",
            "policy":     os.getenv("EDON_HARDENING_POLICY_ENABLED",      "true") == "true",
            "regression": os.getenv("EDON_HARDENING_REGRESSION_ENABLED",  "true") == "true",
        },
        "interval_sec": int(os.getenv("EDON_HARDENING_INTERVAL_SEC", "600")),
    }


@router.post("/seed")
async def seed_hardening_proposal(request: Request):
    """Inject a synthetic approved fix proposal so the hardening loop can run end-to-end.

    Use this in fresh environments where no real shadow findings exist yet.
    The proposal is pre-approved, so the policy agent picks it up immediately
    and generates a rule_ready rule on the next hardening run.

    Safe: the generated rule has enabled=False and status=rule_ready.
    Nothing is applied automatically.
    """
    import uuid as _uuid
    from ..shadow.fix_pipeline import _proposals, _persist, _lock
    from ..tenancy import get_request_tenant_id

    tenant_id = get_request_tenant_id(request)
    now = __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat()

    proposal_id = f"seed-{str(_uuid.uuid4())[:8]}"
    synthetic_proposal = {
        "proposal_id": proposal_id,
        "trace_id": f"synthetic-{str(_uuid.uuid4())[:8]}",
        "perturbation_name": "seed_proposal",
        "perturbation_type": "data_exfiltration",
        "severity": "critical",
        "original_verdict": "ALLOW",
        "shadow_verdict": "BLOCK",
        "perturbed_field": "action_payload",
        "suggested_action": "BLOCK",
        "condition_tool": "database",
        "condition_op": "query",
        "rule_description": "Block bulk database queries from ungoverned agents (seeded by hardening test)",
        "rationale": "Synthetic seed proposal for hardening loop verification. Safe to reject after testing.",
        "tenant_id": tenant_id,
        "agent_id": "hardening-seed",
        "action_type": "database.query",
        "status": "approved",
        "created_at": now,
        "resolved_at": now,
        "resolved_by": "hardening-seed-endpoint",
        "resolution_note": "Auto-approved synthetic seed for loop verification",
    }

    with _lock:
        _proposals[proposal_id] = synthetic_proposal
        _persist()

    logger.info("[hardening/seed] injected synthetic approved proposal: %s", proposal_id)
    return {
        "seeded": True,
        "proposal_id": proposal_id,
        "note": (
            "Synthetic approved proposal created. "
            "Call POST /v1/hardening/run?force=true to run the full coverage→policy→regression cycle."
        ),
    }


@router.get("/rule-ready")
async def get_rule_ready(
    request: Request,
    limit: int = Query(50, le=200),
):
    """Return rules generated by the policy agent, pending operator deployment.

    These rules have passed regression validation (or are flagged for review).
    They are NOT yet in the live policy table.

    Each rule includes:
      - The full rule dict ready for DB insertion
      - The proposal_id it was generated from
      - The regression recommendation (apply | review | reject | inconclusive)
    """
    tenant_id = get_request_tenant_id(request)
    last = _last_results.get(tenant_id or "__global__", {})

    policy_result = last.get("policy") or {}
    regression_result = last.get("regression") or {}

    rules = policy_result.get("rules", [])

    # Merge regression recommendations onto each rule
    regression_reports = {
        r.get("rule", {}).get("proposal_id"): r
        for r in (regression_result.get("reports") or [])
    }

    enriched = []
    for rule in rules[:limit]:
        proposal_id = rule.get("proposal_id")
        reg_report = regression_reports.get(proposal_id, {})
        enriched.append({
            **rule,
            "regression_recommendation": reg_report.get("recommendation", "inconclusive"),
            "regression_bypasses_fixed": reg_report.get("bypasses_fixed", 0),
            "regression_regressions": reg_report.get("regressions", 0),
            "regression_net_improvement": reg_report.get("net_improvement", 0),
        })

    return {
        "rules": enriched,
        "count": len(enriched),
        "note": (
            "These rules are NOT live. Deploy via your policy management API "
            "after reviewing regression_recommendation."
        ),
    }
